import { db } from "./db.js";

const seedProducts = [
  {
    id: "casio-vintage-a1000",
    brandId: "casio",
    name: "Vintage A1000 Gold",
    price: 6500,
    rating: 4.6,
    reviewCount: 3120,
    image: "/images/casio-vintage-gold.jpeg",
    caseColor: "gold",
    dialColor: "#d9c98a",
    strapType: "metal",
    strapColor: "#d4af37",
    caseSizeMm: 35,
    movement: "Quartz",
    caseShape: "Square",
    resistanceM: 30,
    gender: "Unisex",
    warrantyYears: 1,
    description:
      "The iconic 80s digital silhouette in a solid gold-tone finish, with illuminator backlight and stopwatch function.",
    stock: 25,
  },
  {
    id: "gshock-ga2100",
    brandId: "gshock",
    name: "GA-2100 Carbon Core",
    price: 15500,
    rating: 4.8,
    reviewCount: 5410,
    image: "/images/gshock-ga2100-black.jpg",
    caseColor: "black",
    dialColor: "#1c1c1c",
    strapType: "silicone",
    strapColor: "#0d0d0d",
    caseSizeMm: 45,
    movement: "Quartz",
    caseShape: "Square",
    resistanceM: 200,
    gender: "Men",
    warrantyYears: 2,
    description:
      "The 'Casioak' — a carbon-reinforced case built to survive drops, shocks, and daily abuse, rated to 200m water resistance.",
    stock: 40,
  },
  {
    id: "seiko-prospex-diver",
    brandId: "seiko",
    name: "Prospex Diver's 200m",
    price: 28500,
    rating: 4.8,
    reviewCount: 2140,
    image: "/images/seiko-prospex-diver-black.jpg",
    caseColor: "silver",
    dialColor: "#111111",
    strapType: "metal",
    strapColor: "#c7ccd1",
    caseSizeMm: 42,
    movement: "Automatic",
    caseShape: "Round",
    resistanceM: 200,
    gender: "Men",
    warrantyYears: 2,
    description:
      "A classic black dive watch with a unidirectional bezel and 200m water resistance, built on Seiko's proven Prospex platform.",
    stock: 12,
  },
  {
    id: "citizen-eco-drive-corso",
    brandId: "citizen",
    name: "Eco-Drive Corso",
    price: 24500,
    rating: 4.7,
    reviewCount: 940,
    image: "/images/citizen-eco-drive-blue.jpg",
    caseColor: "silver",
    dialColor: "#0f3d73",
    strapType: "metal",
    strapColor: "#c7ccd1",
    caseSizeMm: 40,
    movement: "Quartz",
    caseShape: "Round",
    resistanceM: 100,
    gender: "Men",
    warrantyYears: 5,
    description:
      "Solar-powered Eco-Drive movement means it never needs a battery. A clean blue dial with a sapphire-coated crystal.",
    stock: 8,
  },
  {
    id: "benyar-classic-black",
    brandId: "benyar",
    name: "Classic Automatic Black",
    price: 5500,
    rating: 4.3,
    reviewCount: 612,
    image: "/images/benyar-classic-black.webp",
    caseColor: "silver",
    dialColor: "#1a2530",
    strapType: "metal",
    strapColor: "#c7ccd1",
    caseSizeMm: 40,
    movement: "Automatic",
    caseShape: "Round",
    resistanceM: 50,
    gender: "Men",
    warrantyYears: 1,
    description:
      "A textured navy-black dial paired with a self-winding automatic movement and a solid steel bracelet.",
    stock: 15,
  },
  {
    id: "benyar-sport-orange",
    brandId: "benyar",
    name: "Sport Automatic Orange",
    price: 4800,
    rating: 4.2,
    reviewCount: 388,
    image: "/images/benyar-sport-orange.jpg",
    caseColor: "silver",
    dialColor: "#141414",
    strapType: "metal",
    strapColor: "#c7ccd1",
    caseSizeMm: 40,
    movement: "Automatic",
    caseShape: "Round",
    resistanceM: 50,
    gender: "Men",
    warrantyYears: 1,
    description:
      "Bold orange accents on a black dial give this automatic sport watch a distinct, energetic look.",
    stock: 3,
  },
  {
    id: "benyar-classic-blue-womens",
    brandId: "benyar",
    name: "Classic Automatic Sky Blue",
    price: 4500,
    rating: 4.4,
    reviewCount: 271,
    image: "/images/benyar-classic-blue-womens.jpg",
    caseColor: "silver",
    dialColor: "#aee0e8",
    strapType: "metal",
    strapColor: "#c7ccd1",
    caseSizeMm: 32,
    movement: "Automatic",
    caseShape: "Round",
    resistanceM: 30,
    gender: "Women",
    warrantyYears: 1,
    description:
      "A soft sky-blue textured dial in a compact case, finished with a polished stainless steel bracelet.",
    stock: 10,
  },
  {
    id: "naviforce-teal",
    brandId: "naviforce",
    name: "Classic Teal",
    price: 3200,
    rating: 4.1,
    reviewCount: 505,
    image: "/images/naviforce-teal.jpg",
    caseColor: "silver",
    dialColor: "#1f6b63",
    strapType: "metal",
    strapColor: "#c7ccd1",
    caseSizeMm: 40,
    movement: "Quartz",
    caseShape: "Round",
    resistanceM: 30,
    gender: "Men",
    warrantyYears: 1,
    description:
      "A rich teal sunburst dial with roman numeral markers, dressed up with a solid steel bracelet.",
    stock: 0,
  },
  {
    id: "curren-classic-steel",
    brandId: "curren",
    name: "Classic Steel",
    price: 2800,
    rating: 4.0,
    reviewCount: 214,
    image: "/images/curren-classic-steel.jpg",
    caseColor: "silver",
    dialColor: "#12233d",
    strapType: "metal",
    strapColor: "#c7ccd1",
    caseSizeMm: 42,
    movement: "Quartz",
    caseShape: "Round",
    resistanceM: 30,
    gender: "Men",
    warrantyYears: 1,
    description:
      "An everyday steel quartz watch with a textured black dial — dependable and easy to dress up or down.",
    stock: 20,
  },
  {
    id: "lige-chrono-brown-leather",
    brandId: "lige",
    name: "Chronograph Brown Leather",
    price: 3900,
    rating: 4.3,
    reviewCount: 342,
    image: "/images/lige-chrono-brown-leather.jpg",
    caseColor: "silver",
    dialColor: "#faf9f6",
    strapType: "leather",
    strapColor: "#7a4a2b",
    caseSizeMm: 42,
    movement: "Quartz",
    caseShape: "Round",
    resistanceM: 30,
    gender: "Men",
    warrantyYears: 1,
    description:
      "A working chronograph with a crisp white dial and a genuine croc-embossed leather strap.",
    stock: 18,
  },
  {
    id: "skmei-octagon-digital",
    brandId: "skmei",
    name: "Octagon Sport Digital",
    price: 2400,
    rating: 4.1,
    reviewCount: 742,
    image: "/images/skmei-analog-digital-black.jpg",
    caseColor: "black",
    dialColor: "#2a2a2a",
    strapType: "silicone",
    strapColor: "#161616",
    caseSizeMm: 44,
    movement: "Quartz",
    caseShape: "Square",
    resistanceM: 50,
    gender: "Men",
    warrantyYears: 1,
    description:
      "Analog-digital dual display with alarm, chronograph, and countdown timer functions on a rugged octagonal case.",
    stock: 30,
  },
  {
    id: "olevs-moonphase-blue",
    brandId: "olevs",
    name: "Moonphase Blue Steel",
    price: 3400,
    rating: 4.2,
    reviewCount: 176,
    image: "/images/olevs-moonphase-blue.jpg",
    caseColor: "silver",
    dialColor: "#1c4a8a",
    strapType: "metal",
    strapColor: "#c7ccd1",
    caseSizeMm: 41,
    movement: "Quartz",
    caseShape: "Round",
    resistanceM: 30,
    gender: "Men",
    warrantyYears: 1,
    description:
      "A gradient blue dial with a moonphase complication and crystal hour markers for a dressier everyday look.",
    stock: 5,
  },
];

export function seedProductsIfEmpty() {
  const { count } = db.prepare("SELECT COUNT(*) as count FROM products").get();
  if (count > 0) return;

  const insert = db.prepare(`
    INSERT INTO products (
      id, brand_id, name, price, rating, review_count, image, case_color, dial_color,
      strap_type, strap_color, case_size_mm, movement, case_shape, resistance_m,
      gender, warranty_years, description, stock_quantity
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  for (const p of seedProducts) {
    insert.run(
      p.id,
      p.brandId,
      p.name,
      p.price,
      p.rating,
      p.reviewCount,
      p.image,
      p.caseColor,
      p.dialColor,
      p.strapType,
      p.strapColor,
      p.caseSizeMm,
      p.movement,
      p.caseShape,
      p.resistanceM,
      p.gender,
      p.warrantyYears,
      p.description,
      p.stock,
    );
  }

  console.log(`Seeded ${seedProducts.length} products.`);
}
